### ISSUE TITLE
FileReader leads to excessive memory usage and browser crashes

### ISSUE THREAD

**Issue by KieranP** [216software/ajax-put-rackspace#2]
I'm implementing a file uploader to Rackspace cloud based on the Javascript you've got in this repo. However, I've run into an issue. When I upload a large file, FileReader loads it all into memory, and then the browser crashes. Is there any work around for this? (e.g. read chunks and stream it to rackspace or do whatever a normal form post does - i.e. usually I can upload large files without it reading into memory). Any thoughts?

**Comment by mw44118** [comment]
I'm using readAsArrayBuffer, which explicitly loads everything into memory, so certainly gigantic files will not work.

What is the size of the file that crashes your browser?

You can at least prevent the crash by checking the file's size before you begin the read operation.  But that doesn't solve the real problem.  You want to do the PUT to rackspace (or wherever) and I don't think PUT works outside an AJAX context.  Do browsers let you do PUT in the action attribute now?

A "real" solution would not try to load everything in memory all at once.  Instead, it would give us a socket or pipe or file descriptor or something that we can read from in small amounts and then send along the way.  That must be built-in to the browser already because uploading and downloading gigantic files doesn't cause problems.

The tricky part is that we are doing this in JavaScript.

I found this "createObjectURL" method that MIGHT do what you and I want:

https://developer.mozilla.org/en-US/docs/Web/API/URL.createObjectURL

I saw in the w3 docs how readAsArrayBuffer does load everything into memory, and I didn't see anything abut that in the createObjectURL section, so maybe this will work.

I haven't played around with it yet though.  Can you give it a try?

**Comment by KieranP** [comment]
A file as small as 100mb was crashing my browser tab. Thankfully, after a bit of playing around, I found out you don't need to use FileReader or createObjectURL at all.

XMLHttpRequest supports sending a Blob/File object, which the browser does the right thing with and doesn't load into memory but uploads as a stream. This code both uploads to rackspace, the file makes it intact, and the memory doesn't crash the browser.

Here is a slimmed down version of the code we're using. We do other things like generate the upload URL via an ajax call and use that when upload starts, so no additional page load times are incurred, but I haven't included that code here.

The key in this code is this bit: `data: file`. This does all the magic. No FileReader needed.

``` javascript
$('.upload').submit(function() {
  if (!window.File) {
    alert("Please update to a more modern browser.")
  }

  var file = $(this).find('input[name=file]')[0].files[0];

  $.ajax({
    type: 'PUT',
    url: "....", // Specially crafted rackspace put url
    data: file,
    cache: false,
    contentType: false,
    processData: false,
    success: function() {
      // Make ajax call to save upload details
    }
  });

  return false;
});
```

I suggest you change the code in this repo to behave like this too, so that memory consumption isn't an issue.

**Comment by mw44118** [comment]
That's much better!

Would you send a pull request with this in there?

**Comment by KieranP** [comment]
Done: https://github.com/216software/ajax-put-rackspace/pull/3

It's working great! :-)

**Comment by mw44118** [comment]
Hurray for KieranP!

If you're ever near Cleveland, Ohio, USA, let's meet up!
